apiVersion : apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: mongoapplication
spec:
  progressDeadlineSeconds: 3600
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo 
    spec:
      containers:
        - name: mongo 
          image: mycontainerregistrychabbi.azurecr.io/mongo
          ports:
          - containerPort: 27017
